on:
  push:
  pull_request:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Update apt repos
        run: sudo apt-get update

      - name: Set the correct Node version using nvm
        shell: bash -l {0} 
        run: nvm install

      - name: Install yarn
        shell: bash -l {0} 
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && sudo apt-get update && sudo apt-get install yarn 

      - name: use yarn to install dependencies and deploy
        shell: bash -l {0} 

      - name: Git Setup Global Config
        shell: bash -l {0}
        run: export GITHUB_USER=justinvforvendetta && echo "GITHUB_USER=$GITHUB_USER" >> $GITHUB_ENV && echo "GITHUB_TOKEN=${{ secrets.JUSTINVFORVENDETTA }}" >> $GITHUB_ENV && git config --global user.email "justinvforvendetta@gmail.com" && git config --global user.name $GITHUB_USER

       -name: yarn install and deploy
        shell: bash -l {0}
        run: yarn install && yarn run deploy
        
      - name: Upload site 
        uses: actions/upload-artifact@v3
        with:
          name: vergecurrency.com
          path: |
            ./src/*.js
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3